samber/awesome-prometheus-alerts

_data/rules.yml

In-Sync replicas less than 3 provoke the producer to raise an exception of either NotEnoughReplicas or NotEnoughReplicasAfterAppend.

Adding in-sync replica by topic metric rule

---

_data/rules.yml

Hi
The second query looks wrong to me, it tries to match `probe_http_status_code` metrics which are both equal or lower than 199 and equal or larger than 300 at the same time. I think that this "and" 
was supposed to be an "or". An "and" makes no sense.
I successfully tested the alert with "or" in our env.

correct wrong AND to OR for blackbox_exporter

---

rules.md

I've checked that all 106 rules have a severity field so the value will always be defined.

Take severity value from the rule

---

_data/rules.yml

This rule ensures that probe failures using http, tcp, dns and icmp are discovered.
Currently the StatusCode rule also alert on failed http probes since `probe_http_status_code` will be 0. Maybe that should be changed in order to avoid double alerting?

Add ProbeFailed alert for the Blackbox exporter

---

_data/rules.yml

This rule ensures that [unsuccessful collectors](https://github.com/martinlindhe/wmi_exporter/blob/v0.8.1/exporter.go#L47) for a WMI exporter scrape target are discovered.

Add CollectorError alert for WMI exporter

---

_data/rules.yml

Using the current expression, a node in our cluster is evaluated to have less than 10% of free memory, I hence compared the output of `free` and `cat /proc/meminfo` to learned that the `buff/cache` part is vastly different, the node isn't actually in low memory state.
Here's the output I've mentioned:
```
[root@qcloud-dev2 ~]# free
total        used        free      shared  buff/cache   available
Mem:       16268028     6917832      168252        3616     9181944     5733016
Swap:             0           0           0
[root@qcloud-dev2 ~]# cat /proc/meminfo
MemTotal:       16268028 kB
MemFree:          170024 kB
MemAvailable:    5735232 kB
Buffers:          444924 kB
Cached:           590040 kB
SwapCached:            0 kB
Active:          7025068 kB
Inactive:         561536 kB …
```

free memory should include node_memory_Slab_bytes

---

_data/rules.yml

We can have nodes that are not masters, but don not hold any data. For example the client/coordinating nodes set up by the `stable/elasticsearch` helm chart:
https://github.com/helm/charts/tree/master/stable/elasticsearch#client-and-coordinating-nodes
And we can also have nodes being data and master nodes simultaneously.
So I think, this alert has to look for `es_data_node="true"` to be correct.

elasticsearch: Alert for no new docs on data nodes only

---

_data/rules.yml

The metrics for these alerts return 'instance', not 'ip'
This PR fixes the rules to use 'instance'

Replace 'ip' by 'instance' in some rules

---

_data/rules.yml

Previous rule doesn't work at all. PromQL supports modulo operation, so it's suitable to use it here.

Fix Etcd rule: Insufficient Members

---

_data/rules.yml

`pg_replication_lag` metric does not have consistant value between:
- master
- standby servers
- promoted master
resolve #74

Adding a comment to PostgresqlReplicationLag alert

---

_data/rules.yml

Fixes the rule `PrometheusRuleEvaluationSlow` as it should fire if `prometheus_rule_group_last_duration_seconds` (the duration of the last rule group evaluation) takes longer than `prometheus_rule_group_interval_seconds` (the interval of a rule group).

Fix PrometheusRuleEvaluationSlow

---

_data/rules.yml

Rename it from DeadManSnitch into [DeadManSwitch](https://en.wikipedia.org/wiki/Dead_man's_switch) 🙂

Fix typo in DeadManSwitch alert

---

_data/rules.yml

Added some rules for the apache_exporter :
Not to sure about the last one, maybe useless in certain cases. 
- Apache down : Apache status
- Apache workers load : If workers in busy state is to high
- Apache restart : Apache has restarted in the last minutes

Adding rules for Lusitaniae/apache_exporter

---

_data/rules.yml

Added some rules for the MySQLd_exporter :
Similar to #93 
- MySQL down : MySQL status
- MySQL connections number : Used connections are close to the max connections.
- MySQL slow query count : MySQL server is having slow query.
- MySQL restart : MySQL has been restarted in the last minute.

Adding rules for MySQLd_exporter from prometheus

---

_data/rules.yml

min_over_time takes a time range as parameter
resolving #94 
Thanks @youpai

Fix kubernetes pod not health alert

---

_data/rules.yml

Kube state metrics assigns value of current pod phase with 1, so according to that Kubernetes Pod not healthy fixed. #100

FIX KubernetesPodnothealthy Alert

---

_data/rules.yml

The alarm is now activated only after one hour of non-zero value.
I believe that this behavior was originally intended.

fix "Kubernetes Pod not healthy" query

---

_data/rules.yml

Within `node_exporter` the metric `node_md_disks` exports the following states:
- Active
- Failed
- Spare
In the meantime, it had `fail` instead of `failed`. 
This information can be also confirmed on:
- [Node Exporter collector source code](https://github.com/prometheus/node_exporter/blob/master/collector/mdadm_linux.go#L146)
```go
ch <- prometheus.MustNewConstMetric(
disksDesc,
prometheus.GaugeValue,
float64(mdStat.DisksFailed),
mdStat.Name,
"failed",
)
```
- [Node Exporter fixture for node_md_disks](https://github.com/prometheus/node_exporter/blob/master/collector/fixtures/e2e-output.txt#L1243)
```go
node_md_disks{device="md0",state="active"} 2
node_md_disks{device="md0",state="failed"} 0
node_md_disks{device="md0",state="spare"} 0
```

Fix node_md_disks state from fail to failed

---

_data/rules.yml

The time unit on `node_disk_read_time_seconds_total` is in **seconds**, therefore if we want to evaluate against **100ms** then it should be:
```go
rate(node_disk_read_time_seconds_total[1m]) / rate(node_disk_reads_completed_total[1m]) > 0.1
```
Otherwise it is evaluating **when latency if over 100 seconds**.

Fix time unit on disk read/write latency rule

---

_data/rules.yml

The `container_memory_usage_bytes` considers the cache what is not taken in consideration for OOM kill.
More info: https://medium.com/faun/how-much-is-too-much-the-linux-oomkiller-and-used-memory-d32186f29c9d

fix: container ContainerMemoryUsage alert

---

_data/rules.yml

The original rule was that the mysql server would consistently handle alarm states if a slow query was generated, which didn't seem to make sense.
The new rule is adjusted to alert only if there is a new slow query in the last 2 minutes.

Optimizing mysql slow query alert rules

---

Gemfile.lock
_data/rules.yml

By default prometheus creates target with `job="prometheus"`.
Bundler version upgraded too, otherwise latest jekyll/jekyll docker image won't start with following error:
```
$ docker run --rm -it -p 4000:4000 -v $(pwd):/srv/jekyll jekyll/jekyll jekyll serve
Traceback (most recent call last):
2: from /usr/local/bin/bundle:23:in `<main>'
1: from /usr/local/lib/ruby/site_ruby/2.7.0/rubygems.rb:296:in `activate_bin_path'
/usr/local/lib/ruby/site_ruby/2.7.0/rubygems.rb:277:in `find_spec_for_exe': Could not find 'bundler' (1.17.3) required by your /srv/jekyll/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.17.3`
```

Fix PrometheusJobMissing alert

---

_data/rules.yml

Fixes #7
Metrics in _Traefik_ v2 are basically the same except that `backends` are now referenced as `services`
```
traefik_service_request_duration_seconds_bucket{code="200",method="GET",protocol="http",service="******@kubernetescrd",le="0.1"} 15
traefik_service_request_duration_seconds_bucket{code="200",method="GET",protocol="http",service="******@kubernetescrd",le="0.3"} 15
traefik_service_request_duration_seconds_bucket{code="200",method="GET",protocol="http",service="******@kubernetescrd",le="1.2"} 15
...
traefik_service_requests_total{code="200",method="GET",protocol="http",service="******@kubernetescrd"} 15
...
traefik_service_requests_total{code="401",method="GET",protocol="http",service="******@kubernetescrd"} 5
```

feat(traefik): add rules for Traefik v2

---

rules.md

Service index is reset after each iteration of `group` loop, resulting in duplication of `data-clipboard-target-id` attribute. This mess up with **copy** functionality, that copies only `services` of the first group of alerts.
Adding group index should be enough, to solve this. That should fix #126 at the same time.

Fix data-clipboard-target-id unicity

---

_data/rules.yml

IMHO it would be great to call attention to a better place to deal with unnecessary mount points - at the beginning of the metric lifecycle,
instead of limiting it in alerts, at the end. 
I set up alerts based on this wonderful collection several months ago. I didn't pay attention to the label '{mountpoint="/rootfs"}' in the disk space check rule. This morning my team faced up with failed services. The reason for failure was the lack of free space. It was true - disk was 100% full. But we didn't get any notifications regarding free space. 
So, the default rule doesn't work for us. All our Ubuntu(16-18-20) & Centos(7) nodes have root file mount point as "/", not "/rootfs".
I'm assuming that having an out-of-box working rule will be useful for the community.

check free space for all mountpoints

---

_data/rules.yml

See #90 #113
Because cAdvisor is a piece of 💩  that tracks process info at a very high frequency. Instead of reading /proc at Prometheus scrape time, once every 30s...

Alert on containers CPU: add a comment to exclude cAdvisor

---

_data/rules.yml

Maximum number of pods per node
Typically, on EKS, while using default [Amazon VPC Container Network Interface (CNI)](https://docs.aws.amazon.com/eks/latest/userguide/pod-networking.html), maximum number of pods running is dependent of AWS instance type(cf. [IP addresses per network interface per instance type](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html#AvailableIpPerENI))

feat(kubernetes): add Out of capacity

---

_data/rules.yml

Hey.
In early 2020 the former **wmi_exporter** was moved to the prometheus-community organisation and was renamed to **windows_exporter** (See https://github.com/prometheus-community/windows_exporter/issues/519 for more Infos), which also impacted the name of all metrics.
I updated the rules to match the new exporter name and new metrics.

Adapt rules for windows to new exporter

---

_data/rules.yml

Removing `alert: MongodbReplicationHeadroom` since `mongodb_mongod_replset_oplog_*` have been [deprecated](https://github.com/percona/mongodb_exporter#important-note). 
> Metrics mongodb_mongod_replset_oplog_* doesn't work in Master/Slave replication mode, because it was DEPRECATED in MongoDB 3.2 and removed in 4.0.

remove replset_oplog based alerts

---

_data/rules.yml

The previous approach fails because of the "missing data" semantics in Prometheus. If the Redis server is down, PromQL will typically return "no data" instead of 0 for a `count()`; this is by design in Prometheus.
This suggestion as given by @slovdahl works around this by returning an vector with a single `0` entry in this case, making the query work as intended.

Fix Redis missing master query

---

_data/rules.yml

I found this alert useful to detect instances influenced by noisy neighbors or AWS spot instances out of credits.
Thanks a lot for this very nice collection of alerts! I took a lot of inspiration out of them.

Add cpu steal alert

---

_data/rules.yml

Prometheus `rate` function calculates the per-second average rate of increase. This means the alert gets triggered whenever during last 10 minutes there was less than 1 document ingested *per second* (less than 60 documents per minute) which is not intended.

Fix Elasticsearch "No new documents" alert

---

_data/rules.yml

This change improves the alert by summing up all the heap area entries which include the Eden Space, Survivor Space and Tenured Gen.

JVM alert improvement

---

_data/rules.yml

The rule I removed seems to be a duplicate of the one defined on line 1257
```
- name: Kubernetes Job failed
description: "Job {{$labels.namespace}}/{{$labels.exported_job}} failed to complete"
query: 'kube_job_status_failed > 0'
severity: warning
```
Not sure if it's because of version mismatch somewhere but the above rule did show the namespace/job correctly but for the rule I removed the labels.job_name was blank.

Remove duplicate kubernetes job failed

---

_data/rules.yml

The way this was previously done works for many cases, but in our case we use the `maxmemory` setting to limit the overall Redis memory usage. Hence, the added alternative version.
(Not changed by this MR per se, but worth mentioning here: the `redis_total_system_memory_bytes` data isn't enabled in the Redis exporter unless you activate the `REDIS_EXPORTER_INCL_SYSTEM_METRICS` env variable/command line flag.)
(Quoting https://raw.githubusercontent.com/redis/redis/6.0/redis.conf)
```
############################## MEMORY MANAGEMENT ################################
#
#
#
#
#
```

Redis: add alternative maxmemory alert

---

_data/rules.yml

We have an old minio instance which we can apply the current alert rules on it but we also have a newer minio instance which is exposing total different metrics comparing to the older version of minio, e.g. older minio uses `minio_offline_disks` metrics to tell the number of offline disks but in the new version, it uses `minio_disks_offline` to tell the number of offline disks. I'm not sure since which version they are using the newer metrics

Added new minio alert rules

---

_data/rules.yml

fill in prometheus rules for `instaclustr/cassandra-exporter`
In my case I also expose `instance` field to have a meaningful name because the exporter exposes IPs.
Rules are not tested in real case scenarios but I have mostly used `criteo/cassandra_exporter` existing rules for reference

Fill in PrometheusRules for instaclustr/cassandra-exporter

---

_data/rules.yml

First off, thank you so much for sharing all these alerts! It's been super useful for us!
I'm not sure if this was the initial intention but the existing `KubernetesOutOfCapacity` alert includes pods that have any status including `Evicted`, `Completed` or `Failed` which I believe skews the metric as they are no longer using any resource on the node.
I've updated the query to only take into account Pods that have the status Running to calculate the existing capacity of the node.
Let me know if I'm missing anything.

Improve KubernetesOutOfCapacity alert

---

README.md
_data/rules.yml

Added a few alerts for [loki](https://github.com/grafana/loki), mostly for the new alerting support.
They are quite similar to prometheus' rules.
Ps: prometheus was giving me an error on postgres [rule 23 ](https://awesome-prometheus-alerts.grep.to/rules#rule-postgresql-1-23). I solved by using a pipe and putting the query on a new line

Loki alerts

---

_data/rules.yml

`$labels.interface` doesn't exist, use `$labels.device` instead

fix(HostNetworkInterfaceSaturated): display network interface name

---

_data/rules.yml

When copying the entire section I had trouble getting Prometheus to start, as it could not parse the new rules.
Upon closer inspection I noticed one of the rules had a missing parenthesis.
This PR fixes the rule.

Add missing parenthesis to rule

---

_data/rules.yml

Fix all "percentil" typo to "percentile" in Etcd rules

Fix "percentil" typo in Etcd rules

---

_data/rules.yml

Aggregations require parentheses around expressions

Fix bad syntax for Haproxy rules

---

_data/rules.yml

According to https://github.com/thanos-io/thanos/blob/main/examples/alerts/alerts.md the metric is called `thanos_compact_halted`.

The metric is called 'thanos_compact_halted'

---

_data/rules.yml

When using this alert rule for ‘Kubernetes API client errors’, I found that the `apiserver_request_count` metric was deprecated, after searches through the documentation, it was replaced with a new metric in v1.14.
`apiserver_request_count -> apiserver_request_total`
[Kubernetes CHANGELOG-1.14](https://github.com/kubernetes/kubernetes/blob/8ac5d4d6a92d59bba70844fbd6e5de2383a08c96/CHANGELOG/CHANGELOG-1.14.md)
[Kubernetes CHANGELOG-1.17](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/CHANGELOG/CHANGELOG-1.17.md)

The metric apiserver_request_count has been turned off

---

_data/rules.yml

This rule checks to see if the host requires a reboot using the `node_reboot_required` metric which is generated from the script below using the textfile collector. The metric is based on the contents within the `/var/run/reboot-required` file, usually denoting that kernel updates have been installed and the host requires a reboot for them to take effect.
https://github.com/prometheus-community/node-exporter-textfile-collector-scripts/blob/master/apt.sh

Add rule for reboot-required

---

_data/rules.yml

Hi, this adds alert for network bonds. This works for us with dumb active-passive bonds as well as with LACP 802.3ad on physical hosts.

Add HostNetworkBondDegraded

---

_data/rules.yml

This pull request includes a simple addition of an empty name filter to most of the cAdvisor alert rules to ensure the 'parent' records created by Prometheus do not affect queries and alerting.  See issue #254

fix(rule): Filter docker container 'parent' records (#254)

---

_data/rules.yml

The mysql alert used to observe connection saturation "MySQL too many connections" uses the rate() function on the gauge "mysql_global_status_threads_connected". This is bound to return erroneous values since every decrease in mysql_global_status_threads_connected will be interpreted as a reset of a counter. 
Same reasoning for the seconds alert.
The new query could be even simpler:
`mysql_global_status_threads_connected / mysql_global_variables_max_connections * 100 > 80`
Depending on how often its being evaluated you might miss an intermittent peak in mysql_global_status_threads_connected.

fixed erroneous usage of rate() function on gauges

---

_data/rules.yml

We are using metrics from the alert manager job (e.g. alertmanager_config_last_reload_successful ), but we are not checking if that job is actually there

Added Alert manager job alert

---

.github/workflows/test.yml

Replace unsupported [actions/setup-ruby](https://github.com/actions/setup-ruby) with support [ruby/setup-ruby](https://github.com/ruby/setup-ruby).

Update GH action to use support ruby/setup-ruby

---

.github/dependabot.yml

This will check for updates on any github action which this project uses on a monthly basis.
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

Check for gha updates monthly using dependabot

---

dist/rules/prometheus-self-monitoring/embedded-exporter.yml

A typo was introduced in [the last commit](https://github.com/samber/awesome-prometheus-alerts/commit/f217fabb69072bd1fcbbcf2ff1ee686647398f53), causing validation to fail.
```
$ promtool check rules dist/rules/prometheus-self-monitoring/embedded-exporter.yml
Checking dist/rules/prometheus-self-monitoring/embedded-exporter.yml
FAILED:
dist/rules/prometheus-self-monitoring/embedded-exporter.yml: group "EmbeddedExporter", rule 27, "PrometheusTimeserieCardinality": annotation "description": template: __alert_PrometheusTimeserieCardinality:1: undefined variable "$label"
```

fix(rule): typo in variable name

---

_data/rules.yml

I didn't see any examples like this, and we actually needed this in our environment so we wouldn't get alerted for false positives.

Added query for node warmup before reporing it's down

---

dist/rules/redis/oliver006-redis-exporter.yml

Hi. This rule doesn't seem to make sense,  because in cluster mode. multiple master nodes are normal case.  
In the official tutorial it is recommended to deploy a 3 master 3 slave cluster
```
- alert: RedisTooManyMasters
expr: 'count(redis_instance_info{role="master"}) > 1'
for: 0m
labels:
severity: critical
annotations:
summary: Redis too many masters (instance {{ $labels.instance }})
description: "Redis cluster has too many nodes marked as master.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
```

fix(rule): remove RedisTooManyMasters

---

_data/rules.yml

Was migrated some time ago to https://github.com/prometheus-community/elasticsearch_exporter
Fix #316

fix: Update elasticsearch_exporter repository

---

dist/rules/mysql/mysqld-exporter.yml

The three replication formulas as written were using the value of the server ID (left hand side) instead of the values for io running, sql running, and lag.  On our systems, it immediately alerts and stays open because the server id is > 30 (for lag) and is > 0 (for io running and sql running state).
This change puts the value that needs to be compared on the left hand side of the formula, per the "PromQL Operators" section of the docs (emphasis added by me) :
> `vector1` and `vector2` results in a vector consisting of the elements of `vector1` for which there are elements in `vector2` with exactly matching label sets. Other elements are dropped. **The metric name and values are carried over from the left-hand side vector.**
I am not a promql expert so if there is a better or more …

Reorder mysql metrics in replication alerts

---

_data/rules.yml

`dist` folder is generated by `_data/rules.yml`. The #311 changes automatically reverted on https://github.com/samber/awesome-prometheus-alerts/commit/be76ab09686a262c46a90f740b848c1007f5deeb .

fix: add space for labels `KubernetesJobFailed` alert rule

---

_data/rules.yml

Hi,
I have same issue as mentioned on issues #215 and #253 . I have change the alert and test it on my clusters. With this change the alert is triggered only if the pod is in "unhealthy" state for more than 15 minutes like describe in desciption.
Short  live pods didn't trigger anymore this alert.
Regards.

fix(rule): fixing KubernetesPodNotHealthy (#215 #253)

---

_data/rules.yml

Relates to issue #327 
1. add **comment** for [BlackboxSslCertificateExpired](https://awesome-prometheus-alerts.grep.to/rules#rule-blackbox-1-7)  to make clear that this rule will only work when `insecure_skip_verify` is enabled in the *blackbox_exporter* module.
2. use [last_over_time](https://prometheus.io/docs/prometheus/latest/querying/functions/#aggregation_over_time) in all three certificate rules to make them less prone to alert flapping. Alert flapping can happen when metrics disappear which can happen when a scrape/probe fails.
3. add **lower bound thresholds** on [BlackboxSslCertificateWillExpireSoon](https://awesome-prometheus-alerts.grep.to/rules#rule-blackbox-1-5) rules to avoid overlap. When time-to-expire < 0, it is also < 3 and < 30. This way no `inhibit_rules` are …

Cert rules issues

---

_data/rules.yml

This alert should inform when HPAs are scaled more than half the time at their minReplicas, which is an indication of possible cost savings. In addition, it is assumed that a minimum number of replicas should still be running for redundancy.

Add under-utilized HPA alert

---

_data/rules.yml

Use `elasticsearch_indices_indexing_index_total` instead of `elasticsearch_indices_docs` because `elasticsearch_indices_docs` might not update without an index refresh [1]. Refreshes happen every second by default, *but* only if there have been search requests within the last 30 seconds [2]. If there are no search requests for a sufficiently long duration, the alert based on `elasticsearch_indices_docs` will fire mistakenly.
Apart from that, `elasticsearch_indices_docs` has the gauge metric type (while `elasticsearch_indices_indexing_index_total` is of the counter type) and the `increase` function is not intended to be used with gauges. Drops in the document count would be treated as a reset to 0, thus showing an increase by all remaining documents.
[1]: …

Make ElasticsearchNoNewDocuments alert more robust

---

_data/rules.yml

I know there's a node exporter metric for ZFS, but on my proxmox host node exporter is not built with it enabled. So better to have both I think.

Add APC UPS & ZFS exporter

---

dist/rules/host-and-hardware/node-exporter.yml

Ignore temperature from tctl sensors: the tctl sensor is not a real hardware component and will report numbers in the 80's or 90's thus triggering the alarm even when the cores are around 30c.

Ignore temperature from tctl sensors

---

_data/rules.yml

The `mongodb_rs_members_optimeDate` metric is in milliseconds, the replication lag query has been updated to reflect this.

Update MongoDB replication lag alert to use seconds

---

_data/rules.yml

refactor: node-exporter queries to include hostname as label which will be helpful for alerting. Before it used to show only ip address but with this small change it's going to show nodename/hostname

refactor: node-exporter queries to include hostname as label 

---

_data/rules.yml

It seems that from my point of view the `nginx latency` rule is missing a parameter for the sum (`le`).
Indeed, this query needs to have the `le` inside the sum if you want to work with quantile.
It's close to the following comment : https://github.com/samber/awesome-prometheus-alerts/issues/292#issuecomment-1175848201
Thanks ! :)

fix(nginx): fix nginx query for histogram_percentile

---

dist/rules/istio/embedded-exporter.yml

IstioLatency99Percentile is in milliseconds so to have 1s we need to set 1000 instead of 1

Fix threshold for IstioLatency99Percentile

---

_data/rules.yml

If the host clock is out of sync NTP will gradually correct it. `10m` should be a sufficient time for the system clock to correct while preventing false positives alerts.

Update Clock Skew Offset

---

_data/rules.yml
dist/rules/postgresql/postgres-exporter.yml

Postgres does not limit connections by database, but total over the server. Additionally, alert labels didn't match across the pair. Using a min by on the right side deals with the possibility additional labels are present on your exporter.

Fix for Postgres max connections. 

---

_data/rules.yml

From my naive understanding, suppose we have 2 redis instances (1x master, 1x slave). Then, I observe `redis_connected_slaves` has two series, one having value 1 and another having value 0.
Then, `count` gives 2 and `sum` gives 1. Thus LHS yields `2 - 1 - 1 = 0`.
Now, suppose the slave is disconnected. Then the LHS yields `2 - 0 - 1 = 1`. So we should set `>0` not `>1` as condition.

Fix `Redis disconnected slaves` off-by-one

---

_data/rules.yml
dist/rules/kubernetes/kubestate-exporter.yml

- provide meaningful labels in summary as 'instance' label hardly makes sense in most of them
- rename some alerts to tell more accurate what the problem is
- adjust description trying to follow some kind of the schema found in other alerts

Rework kube-state-metrics alerts

---

alertmanager.md

This typo would cause the example pager route to never be triggered.

Fix typo "critial" in receiver routes

---

dist/rules/host-and-hardware/node-exporter.yml

… instead of rate, since node_memory_MemAvailable_bytes is a gauge.
Fixes #399

Update rule for host memory underutilization to use avg_over_time

---

_data/rules.yml

If memory limit for Redis instance is not set then redis_memory_max_bytes metric equals 0 - https://github.com/oliver006/redis_exporter?tab=readme-ov-file#the-redis_memory_max_bytes-metric
In that case expression `redis_memory_used_bytes / redis_memory_max_bytes * 100 > 90` return `+Inf` that fires RedisOutOfConfiguredMaxmemory alert.
So we additionally need to check `redis_memory_max_bytes > 0` condition

RedisOutOfConfiguredMaxmemory: checking if memory limit is set

---

_data/rules.yml

This merge request adds new alert definitions for monitoring indexing and query metrics related to Elasticsearch. These alerts are crucial for detecting and mitigating potential performance issues in Elasticsearch clusters.

add new alerts for elasticsearch rules.yml

---

_data/rules.yml
dist/rules/clickhouse/embedded-exporter.yml

Added Clickhouse

---

_data/rules.yml

Correct rule expression evaluation...
Current rule expression evaluation...

Fixed HPA rule to use more correct condition

---

_data/rules.yml

haproxy_backend_max_sessions is the maximum number of sessions ever encountered during the lifetime of the HAProxy process. That is, it will never go down until HAProxy is restarted, so the alert continues to fire even though the situation has cleared!
This doesn't make sense. Look at the currently active sessions instead.

Fix HaproxyBackendMaxActiveSession: look at current / limit

---

_data/rules.yml

It's more accurate to use this way to track sudden changes.

fix elasticsearch rate rules

---

_data/rules.yml
dist/rules/meilisearch/embedded-exporter.yml

this should add a basic set of rules for meilisearch, i would like to expand this in the future when we will add more in our production cluster.
Documentation for metrics is here: https://www.meilisearch.com/docs/learn/experimental/metrics
im not supergood at this but i want to give something back to the community! :D

feat(meilisearch): add basic set of rules

---

_data/rules.yml

Hello there! 👋 
A Pull Request to add a new rule - that I needed to add on my side - in order to monitor Kubernetes jobs which do not start for more than 10 minutes (for instance if the resource quota is full).
A bit similar to rollout stuck rules.
First PR here, so I hope I did not make any mistake but feel free to give any suggestions/feedback! :)

feat: Add rule to Kubernetes Job not starting

---

_data/rules.yml
dist/rules/rabbitmq/rabbitmq-exporter.yml

This alert might be useful for systems that aren't 100% stable. In my case I didn't notice that my consumers stopped at a point, and as a result, ready messages piled up to half a million.

RabbitMQ: add too many ready messages alert

---

_data/rules.yml

Added missing parentheses to a `node-exporter` rule, which led to parsing error
```
bad prometheus expr: "(rate(node_disk_read_time_seconds_total[1m]) / rate(node_disk_reads_completed_total[1m]) > 0.1 and rate(node_disk_reads_completed_total[1m]) > 0", err: parensExpr: unexpected token ""; want "," or ")"; unparsed data: ""
```

fix missing parentheses in node-exporter rule

---

_data/rules.yml
dist/rules/elasticsearch/prometheus-community-elasticsearch-exporter.yml

The `elasticsearch_indices_search_fetch_total`,
`elasticsearch_indices_search_fetch_time_seconds`, `elasticsearch_indices_indexing_index_time_seconds_total` and `elasticsearch_indices_indexing_index_total` metrics are counters.
Dividing these metrics doesn't make sense because a spike in numerator would cause the alert to persist, even if subsequent fetch/index operations are normal. Adding `increase` changes the query to check if operations took, on average, more than X over a 1-minute interval, which was likely the original intent of this alert.

Fix queries in elasticsearch latency alerts

---

_data/rules.yml
dist/rules/postgresql/postgres-exporter.yml

First of all, thank you so much for providing these awesome alert rules! 🙂 Keep up the great work
This PR adds a `PostgresqlReplicationLagHigh` rule that triggers when the **replication lag** is higher than **60 seconds**. This should help teams detect **potential replication issues** before they become critical.
I hope it can be a good addition :) let me know what you think

Added PostgresqlReplicationLagHigh rule

---

_data/rules.yml

The alert "HAProxy backend max active sessions > 80%" for the V2 exporter is not aligned with the one from the V1 exporter, which [received a fix](https://github.com/samber/awesome-prometheus-alerts/pull/413) to use the metrics that expose the current values instead of a monothonic increasing value. 
This PR aims to align the behavior on both exporters using the correct metrics also in V2

haproxy: align v1 and v2 HAProxy backend max active session > 80% alerts
