samber/awesome-prometheus-alerts

- _data/rules.yml
> Elasticsearch alert rules

- _data/rules.yml
Plz look on my fixes for node exporter
My node_exporter version is 0.16.0. This is not latest node_exporter, but this changes useful for me
> fome fixes for node exporter rules

- _data/rules.yml
> Add blackbox rules

- README.md
- _data/rules.yml
Add some very basic Juniper rules from czerwonk/junos_exporter.
> Add Juniper rules

- _data/rules.yml
> node-exporter: better cpu load query

- _data/rules.yml
- Container Memory Usage
- Container Volume Usage
- Swap is filling up
> Suggest fix rules

- _data/rules.yml
I add two example alerts for Traefik. Solves #7.
> add alerts for traefik

- README.md
- _data/rules.yml
> Add OpenEBS and Minio alert

- CONTRIBUTING.md
- _layouts/default.html
- assets/css/app.css
- assets/js/app.js
- docker-compose.yml
- rules.md
> Adding copy buttons

- _data/rules.yml
Match other alert names, without the `has` part.
> SllCertificateExpired synthax

- alertmanager.md
> Fixed typo in alertmanager.md

- _data/rules.yml
Two alerts to capture Overtemperature scenarios on physical hardware.
> Added hardware temperature alerts

- _data/rules.yml
Useful to see if you're going to have a disk space problem before you go home 😃!
> Added "Disk will fill in 4 hours" alert

- _data/rules.yml
> Added RAID alerts (node-exporter)

- _data/rules.yml
resolve https://github.com/samber/awesome-prometheus-alerts/issues/60
> Adding alerts for criteo/cassandra_exporter

- _data/rules.yml
Two rules, an upload and download speed test alert.
> Add initial Speedtest Exporter rules

- _data/rules.yml
Detect increase in transmit or receive network errors.
> Network transmit errors

- _data/rules.yml
- alertmanager.md
`error` is a log level
`critical` is more suited here
Discussed here => #109
> Replacing "error" severity by "critical", repo wide

- _data/rules.yml
Suggested by @fernandocarletti in #119
> Fix container memory limit: filter containers having memory limit

- _data/rules.yml
- Fixing KubernetesHpaMetricAvailability
- Fixing KubernetesHpaScalingAbility
> [PLEASE_MERGE] Fix HPA alerts

- _data/rules.yml
> Add official RabbitMQ exporter rules

- rules.md
`True || whatever` is always true.
> fix: remove unnecessary test

- _data/rules.yml
Rule to ensure connection speed of NIC is 1Gb.
> Add HostNetworkNot1GbSpeed rule

- _data/rules.yml
Closes #141 
Thanks @therb1 for your contribution!
> Adding Cassandra alerts

- rules.md
> Fix rule template: removing quotes

- _data/rules.yml
> istio alert rules

- _data/rules.yml
Hi, here is some rules for haproxy >=2
I also "prettified" the yaml thanks to `prettier`, I can remove this commit if needed, or open another PR with only this commit.
ref #87
> chore: add Prometheus alerts for HAProxy v2

- _data/rules.yml
Hi, here is small improvements on haproxy 2 rules
> refactor: improve some haproxy v2 rules

- _data/rules.yml
Took the default rules from the vmware_exporter and added them into this PR for issue #176
> Adding some basic rules snagged from the defaults.

- _data/rules.yml
Fix rule.
Signed-off-by: Bertrand Mailhe <bmailhe@leadformance.com>
> fix rule -Container Volume usage-

- _data/rules.yml
A few alerts I've been using with https://pypi.org/project/prometheus-freeswitch-exporter/
> feat(freeswitch)

- _data/rules.yml
> fix(haproxy)

- _data/rules.yml
The're quite clear on how they want it to be written:
https://unix.stackexchange.com/review/suggested-edits/372414
> Fix upper/lowercase of systemd

- _data/rules.yml
Hi! 
I pushed some fixes and useful description, I tried to comment changes in commits
> Haproxy 2  embedded exporter fixes

- _data/rules.yml
Added cortex alerts to:
- Ingester
- query-frontend
> added alerts to cortex

- README.md
- _data/rules.yml
Adding simple alerts for Hashicorp Vault.
Easy and fast get status about Vault - up/down or sealed/unsealed
Also some additional alerts about Infinity tokens and pending tokens.
> Add alerts for Hashicorp Vault

- README.md
- _data/rules.yml
Adding alerts to:
- Loki
- Promtail
> adding alerts to promtail and loki

- _data/rules.yml
This PR adds some simple Solr rules for its embedded exporter.
> Add Solr rules

- _data/rules.yml
Hi,
Thank for all rules. I add the `auto` in order to match the query.
Best
> docs(postgres): add auto prefix in order to match query

- _data/rules.yml
- dist/rules/kubernetes/kubestate-exporter.yml
added NetworkUnavailable node alert.
remove OutOfDisk alert, cause OutOfDisk condition was removed from kubelet side. 
https://github.com/kubernetes/kubernetes/pull/72507
> fix: added NodeNetworkUnavailable alerts, rm unused OOD alert

- dist/rules/cassandra/instaclustr-cassandra-exporter.yml
> fix typo in instaclustr-cassandra-exporter.yml

- dist/rules/host-and-hardware/node-exporter.yml
> disk io ops alarm

- _data/rules.yml
- dist/rules/hashicorp-vault/embedded-exporter.yml
@samber : Hashicorp Vault cluster health alert
> Hashicorp Vault cluster health

- _data/rules.yml
Rules for various Thanos Components.
> Adding more rules for Thanos Monitoring

- dist/rules/kubernetes/kubestate-exporter.yml
Better wording for NodeReady nodes
> Rename KubernetesNodeReady alert

- dist/rules/redis/oliver006-redis-exporter.yml
use max allowed connections value instead of a fixed value
> feat: improve rule for used connection on redis

- _data/rules.yml
- dist/template.yml
https://github.com/samber/awesome-prometheus-alerts/issues/383
> Add simple and meaningful `kube-state-metrics` alert summary

- README.md
- _data/rules.yml
- dist/rules/graph-node/embedded-exporter.yml
https://github.com/graphprotocol/graph-node
> feat: Add rules for Graph Node

- _data/rules.yml
In order to lint I used [pint](https://github.com/cloudflare/pint)
> fix: some kube api alert lint

- _data/rules.yml
- dist/rules/kubernetes/kubestate-exporter.yml
In order to lint I used [pint](https://github.com/cloudflare/pint)
> kube hpa lint and improvement

- _data/rules.yml
- dist/rules/host-and-hardware/node-exporter.yml
> fix: formatting errors

- README.md
- _data/rules.yml
- dist/rules/caddy/embedded-exporter.yml
adding caddy.
please correct me if something is not correct.
> Add caddy.yml

- _data/rules.yml
update istio 4xx alert description
> update istio 4xx alert description

- _data/rules.yml
> fix: HostHighCpuUsage

- _data/rules.yml
- dist/rules/clickhouse/embedded-exporter.yml
These new alerts use default metrics provided by the built-in ClickHouse Prometheus exporter, ensuring accurate and reliable monitoring of essential ClickHouse performance and health indicators.
> add : additional essential clickhouse alerts
